language: python
python:
  - "3.6"

# Install the following packages(dependencies)
install:
  - pip install -r requirements.txt

# Run tests
script:
  - pytest --cov-report term-missing --cov=api

    
# Mark it as tested successfully with coveralls
after_success:
  - coveralls

cache: pip