language: python
python:
  - "3.6.2"
cache: pip

# Install the following packages(dependencies)
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

# Run tests
script:
    - nosetests --with-coverage --cover-tests --cover-package=tests
    
# Mark it as tested successfully with coveralls
after_success:
  - coveralls
