language: python
python:
  - "3.6"
cache: pip

# Install the following packages(dependencies)
install:
  - pip install -r requirements.txt

# Run tests
script:
 - pytest
    - py.test --cov=api
    
# Mark it as tested successfully with coveralls
after_success:
- coveralls


language: python
python:
    - "3.6"


# Install dependencies
install:
    - pip install -r requirements.txt

# Run tests
script:
    - pytest
    - py.test --cov=api --with


after_success:
- coveralls